# -*- coding: utf-8 -*-
"""MLBD_LAB6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OFMvqycxae4sLo7aqwQskbvywO-DT960
"""

import sklearn
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

# Wczytanie zbioru danych diabetes
diabetes=pd.read_csv("diabetes.csv")
diabetes

# Sprawdzanie wartości null
cols_missing = [col for col in diabetes.columns
                     if diabetes[col].isnull().any()]
for i in cols_missing:
    print(i,sum(diabetes[i].isnull()))

diabetes.describe()

# Histogramy dla każdej kolumny
histogram = diabetes.hist(figsize = (20,20), rwidth=0.9,color='skyblue')

diabetes_copy = diabetes.copy()

cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
diabetes_copy[cols] = diabetes_copy[cols].replace({0 : np.nan})

# Sprawdzanie wartości null
cols_missing = [col for col in diabetes_copy.columns
                     if diabetes_copy[col].isnull().any()]
for i in cols_missing:
    print(i,sum(diabetes_copy[i].isnull()))

diabetes_copy.describe()

# Zamiana wartości null na średnie
diabetes_copy['Glucose'].fillna(diabetes_copy['Glucose'].mean(), inplace = True)
diabetes_copy['BloodPressure'].fillna(diabetes_copy['BloodPressure'].mean(), inplace = True)
diabetes_copy['SkinThickness'].fillna(diabetes_copy['SkinThickness'].median(), inplace = True)
diabetes_copy['Insulin'].fillna(diabetes_copy['Insulin'].median(), inplace = True)
diabetes_copy['BMI'].fillna(diabetes_copy['BMI'].median(), inplace = True)

# Histogamy
p = diabetes_copy.hist(figsize = (20,20), rwidth=0.9,color='skyblue')

# Sprawdzanie wartości null
cols_missing = [col for col in diabetes_copy.columns
                     if diabetes_copy[col].isnull().any()]
for i in cols_missing:
    print(i,sum(diabetes_copy[i].isnull()))

# Podział danych
X = diabetes_copy.drop("Outcome",axis=1)
y= diabetes_copy["Outcome"]

# Podział zbioru danych na zbiór uczący i zbiór testowy
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('X_train: ', np.shape(X_train))
print('y_train: ', np.shape(y_train))
print('X_test: ', np.shape(X_test))
print('y_test: ', np.shape(y_test))

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

# Utworzenie klasyfikatora SVM
svm = SVC(kernel='linear', C=1, gamma='auto')

# Trenowanie klasyfikatora na zbiorze uczącym
svm.fit(X_train, y_train)

# Przewidywanie wartości dla zbioru testowego
y_pred = svm.predict(X_test)

# Obliczenie dokładności klasyfikacji dla zbioru testowego
score = accuracy_score(y_test, y_pred)

print("Dokładność klasyfikacji:", score)

param_grid = {'C': [0.1, 1, 10, 100],
              'gamma': [0.1, 1, 10, 100, 'auto'],
              'kernel': ['sigmoid', 'rbf']}

# Define SVM model
model = SVC()

# Perform grid search
grid_search = GridSearchCV(model, param_grid=param_grid, cv=5)
grid_search.fit(X_train, y_train)

# Print best parameters and score
print("Najlepsze parametry: ", grid_search.best_params_)
print("Dokładność klasyfikacji:", grid_search.best_score_)

# zdefiniowanie i dopasowanie modelu drzewa decyzyjnego
model_dt = DecisionTreeClassifier(random_state=0, max_depth=3)
model_dt.fit(X_train, y_train)

# ocena skuteczności modelu na zbiorze testowym
predictions = model_dt.predict(X_test)
accuracy_dt = accuracy_score(y_test,predictions)
print("Dokładność klasyfikacji:", accuracy_dt)

# zdefiniowanie i dopasowanie modelu KNN
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# Przewidywanie etykiet dla zbioru testowego
y_pred = knn.predict(X_test)

# ocena skutecznoścu modelu na zbiorze testowym
score_knn = knn.score(X_test, y_test)
print("Dokładność klasyfikacji:", score_knn)
